USE cbb_data;

CREATE TABLE IF NOT EXISTS season_stats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    School VARCHAR(255),
    G INT,
    W_Tot INT,
    L_Tot INT,
    W_L_Percentage FLOAT,
    Simple_Rating_System FLOAT,
    Strength_Of_Schedule FLOAT,
    W_Conf INT,
    L_Conf INT,
    W_Home INT,
    L_Home INT,
    W_Away INT,
    L_Away INT,
    Tm_Pts FLOAT,
    Opp_Pts FLOAT,
    MP FLOAT,
    FG FLOAT,
    FGA FLOAT,
    FG_Percentage FLOAT,
    ThreeP FLOAT,
    ThreePA FLOAT,
    ThreeP_Percentage FLOAT,
    FT FLOAT,
    FTA FLOAT,
    FT_Percentage FLOAT,
    ORB FLOAT,
    TRB FLOAT,
    AST FLOAT,
    STL FLOAT,
    BLK FLOAT,
    TOV FLOAT,
    PF FLOAT,
    Season YEAR
);
